name: .NET build and run

on:
  push:
    branches: [ "main" ] # ודאי שזה שם הענף שלך
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' 

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Application
      env:
        # אלו השמות שקבענו ב-Program.cs וב-Secrets
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: dotnet run --no-build
