name: .NET build and run

on:
  push:
    branches: [ "master" ] # מעודכן לפי הצילום מסך שלך
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' 

    - name: Restore
      run: dotnet restore ./PortfolioApi/PortfolioApi.csproj # הוספת נתיב מפורש

    - name: Build
      run: dotnet build ./PortfolioApi/PortfolioApi.csproj --no-restore

    - name: Run Application
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # כאן אנחנו אומרים לו בדיוק איזה פרויקט להריץ
      run: dotnet run --project ./PortfolioApi/PortfolioApi.csproj --no-build
